version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine3.17
    container_name: todos-postgres
    env_file:
      - ".env"
    ports:
      - "5433:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: todos-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
